//
// Generated file, do not edit! Created by opp_msgc 4.3 from PingMessage.msg.
//

#ifndef _PINGMESSAGE_M_H_
#define _PINGMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>PingMessage.msg</tt> by opp_msgc.
 * <pre>
 * message PingMessage {
 *     string peerId;
 * }
 * </pre>
 */
class PingMessage : public ::cMessage
{
  protected:
    opp_string peerId_var;

  private:
    void copy(const PingMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PingMessage&);

  public:
    PingMessage(const char *name=NULL, int kind=0);
    PingMessage(const PingMessage& other);
    virtual ~PingMessage();
    PingMessage& operator=(const PingMessage& other);
    virtual PingMessage *dup() const {return new PingMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getPeerId() const;
    virtual void setPeerId(const char * peerId);
};

inline void doPacking(cCommBuffer *b, PingMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PingMessage& obj) {obj.parsimUnpack(b);}


#endif // _PINGMESSAGE_M_H_
